name: ci

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read

    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.21'
          check-latest: true

      - uses: chainguard-dev/actions/goimports@2cadca168a422313df94f6169691a86498ae51b1 # main
      - run: make wolfictl
      - run: make test

  wolfictl-text:
    permissions:
      contents: read

    name: wolfictl text on wolfi-dev/os
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.21'
          check-latest: true

      - run: make wolfictl
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          repository: 'wolfi-dev/os'
          path: 'wolfi-os'
      - name: Test Wolfi OS repo
        run: |
          ./wolfictl text -d wolfi-os \
            --type=name \
            --pipeline-dir=wolfi-os/pipelines/ \
            --keyring-append=https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub \
            --repository-append=https://packages.wolfi.dev/bootstrap/stage3

      - name: Test nested repo structure
        run: |
          ./wolfictl text -d testdata/text/ | grep foo-0.0.2-r0
          ./wolfictl text -d testdata/text/ | grep bar-0.0.1-r0
          ./wolfictl text -d testdata/text/ | grep root-0.0.1-r0
